Backend: Vivado
Board: null
ClockPeriod: 5
HLSConfig:
  LayerName:
    average_pooling2d:
      Precision: ap_fixed<16,6>
      ReuseFactor: 16
      Trace: true
    batch_normalization:
      Precision:
        bias: ap_fixed<16,6>
        scale: ap_fixed<16,6>
      ReuseFactor: 16
      Trace: true
    batch_normalization_1:
      Precision:
        bias: ap_fixed<16,6>
        scale: ap_fixed<16,6>
      ReuseFactor: 16
      Trace: true
    batch_normalization_2:
      Precision:
        bias: ap_fixed<16,6>
        scale: ap_fixed<16,6>
      ReuseFactor: 16
      Trace: true
    input_1:
      Precision:
        result: ap_fixed<16,6>
      ReuseFactor: 16
      Trace: true
    q_activation:
      Precision:
        result: ap_ufixed<8,0>
      ReuseFactor: 16
      Trace: true
    q_activation_1:
      Precision:
        result: ap_ufixed<8,0>
      ReuseFactor: 16
      Trace: true
    q_activation_2:
      Precision:
        result: ap_ufixed<8,0>
      ReuseFactor: 16
      Trace: true
    q_dense:
      Precision:
        bias: ap_fixed<12,4>
        weight: ap_fixed<12,4>
      ReuseFactor: 16
      Trace: true
    q_dense_1:
      Precision:
        bias: ap_fixed<12,4>
        weight: ap_fixed<12,4>
      ReuseFactor: 16
      Trace: true
    q_dense_2:
      Precision:
        bias: ap_fixed<12,4>
        weight: ap_fixed<12,4>
      ReuseFactor: 16
      Trace: true
    q_dense_3:
      Precision:
        bias: ap_fixed<12,4>
        weight: ap_fixed<12,4>
      ReuseFactor: 16
      Trace: true
  Model:
    Precision: ap_fixed<18,6>
    ReuseFactor: 16
    Strategy: Resource
  SkipOptimizers:
  - relu_merge
IOType: io_stream
InputData: null
KerasModel: !keras_model './my-hls-test/keras_model.h5'
OutputDir: ./my-hls-test
OutputPredictions: null
ProjectName: myproject
Stamp: 1BF42eD6
XilinxPart: xcu200-fsgd2104-2-e
